In [2]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [3]:
df = pd.read_csv('titanic_train.csv')
df.head()

Survived  Pclass  Sex  Age  SibSp  Parch     Fare  Embarked_C  Embarked_Q  \
0         0       3    0   22      1      0   7.2500           0           0   
1         1       1    1   38      1      0  71.2833           1           0   
2         1       3    1   26      0      0   7.9250           0           0   
3         1       1    1   35      1      0  53.1000           0           0   
4         0       3    0   35      0      0   8.0500           0           0   

   Embarked_S  
0           1  
1           0  
2           1  
3           1  
4           1

In [4]:
X = df.drop(columns=['Survived'])
X.head()

Pclass  Sex  Age  SibSp  Parch     Fare  Embarked_C  Embarked_Q  Embarked_S
0       3    0   22      1      0   7.2500           0           0           1
1       1    1   38      1      0  71.2833           1           0           0
2       3    1   26      0      0   7.9250           0           0           1
3       1    1   35      1      0  53.1000           0           0           1
4       3    0   35      0      0   8.0500           0           0           1

In [5]:
y = df['Survived']
y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [6]:
print(df.shape)
print(X.shape)
print(y.shape)

(714, 10)
(714, 9)
(714,)


In [7]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=45)

In [8]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(535, 9)
(179, 9)
(535,)
(179,)


In [9]:
model = LogisticRegression()

In [10]:
model.fit(X_train,y_train)

c:\Users\saura\anaconda3\envs\titanic_env\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [11]:
y_pred = model.predict(X_test)

In [12]:
y_pred[15:20]

array([1, 0, 0, 1, 0], dtype=int64)

In [13]:
y_test[15:20]

513    1
410    0
146    1
9      1
137    0
Name: Survived, dtype: int64

In [14]:
cnf_mat = confusion_matrix(y_test,y_pred)
cnf_mat

array([[88, 19],
       [23, 49]], dtype=int64)

In [15]:
accuracy_score(y_test,y_pred)

0.7653631284916201

In [16]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.79      0.82      0.81       107
           1       0.72      0.68      0.70        72

    accuracy                           0.77       179
   macro avg       0.76      0.75      0.75       179
weighted avg       0.76      0.77      0.76       179



In [17]:
import json

with open('encoder.json','r') as f:
    encoder_dict = json.load(f)

encoder_dict

{'columns': ['Pclass',
  'Sex',
  'Age',
  'SibSp',
  'Parch',
  'Fare',
  'Embarked_C',
  'Embarked_Q',
  'Embarked_S'],
 'sex': {'male': 0, 'female': 1}}

In [18]:
Pclass = 3
Sex = 'male'
Age = 22
SibSp = 1
Parch = 0
Fare = 7.25
Embarked = 'Embarked_'+'S'

In [19]:
Sex = encoder_dict['sex'][Sex]
Sex

0

In [20]:
encoder_dict['columns'].index(Embarked)

8

In [21]:
test_array = np.zeros(len(encoder_dict['columns']))
test_array.shape

(9,)

In [22]:
test_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
test_array[0] = Pclass
test_array[1] = Sex
test_array[2] = Age
test_array[3] = SibSp
test_array[4] = Parch
test_array[5] = Fare
test_array[encoder_dict['columns'].index(Embarked)] = 1

test_array

array([ 3.  ,  0.  , 22.  ,  1.  ,  0.  ,  7.25,  0.  ,  0.  ,  1.  ])

In [24]:
model.predict([test_array])

c:\Users\saura\anaconda3\envs\titanic_env\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [25]:
import pickle

with open('model.pkl','wb') as f:
    pickle.dump(model,f)

In [26]:
with open('model.pkl','rb') as f:
    model_test = pickle.load(f)

model_test.predict([test_array])

c:\Users\saura\anaconda3\envs\titanic_env\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0], dtype=int64)